## YAML Template.
name: AutoFillHole
main: holeFiller.HoleFiller
version: 0.3.2
api-version: 1.16
author: M0rica
website: https://github.com/M0rica/AutoFillHole-Plugin
commands:
    fillhole:
        description: something
        usage: "Usage: /fillhole"
