## YAML Template.
name: AutoFillHole
main: holeFiller.HoleFiller
version: 0.3
api-version: 1.16
author: M0rica
website: PLACEHOLDER
commands:
    fillhole:
        description: something
        usage: "Usage: /fillhole x y z"
